.\" Copyright (C) 2009 Red Hat, Inc. All Rights Reserved.
.\" Written by Ivana Hutarova Varekova <varekova@redhat.com>
.TH DUMP_UTMP 8 "2009 December 2" "Linux accounting system"

.SH NAME
dump\-utmp \- print a utmp file in human-readable format

.SH SYNOPSYS
\fBdump-utmp\fR [\fB-hrR\fR] [\fB-n\fR <\fIrecs\fR>] <\fBfiles\fR>
      [\fB--num\fR <\fIrecs\fR>] [\fB--raw\fR] [\fB--reverse\fR] [\fB--help\fR]

.SH OPTIONS
The following options are supported:
.TP
.B -h, --help
Print a help message and the default location of the process accounting file
and exit.
.TP
.B -r, --reverse
Print the output in reverse order.
.TP
.B -R, --raw
The records will be printed without any parsing.
.TP
.B -n, --num NUMRECS
Display only the first NUMRECS number of records.

.SH SEE ALSO
accton (8), lastcomm (1), utmp (5)
